# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97b27c825dce6d09ed0c7bd686312c7cf0a5c527858d1f07cc61495aa86dec802a65631ed7ed0891d1af972ce1411ca4c3e30f6c767c0a14676abe69a5698577

test:
  secret_key_base: 2ade2bd5cb1fe949981c84593b8025d8519fc6471f0a9ccb8278b1b50feade4d571718db6f4a82b92599a4826d88c2f9a3c6a485aeb1fe27c980b17f2b8718ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
